{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "REPLACE_ME_APP_NAME.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  hosts:
  {{ if eq .Release.Name "prod" }}
  {{- range .Values.virtualService.productionHosts }}
  - {{ . }}
  {{- end }}
  {{ if eq .Values.virtualService.productionGateway "public-gateway.prod" -}}
  - {{ template "REPLACE_ME_APP_NAME.fullname" . }}.public.angha.me
  {{ else if eq .Values.virtualService.productionGateway "private-gateway.prod" -}}
  - {{ template "REPLACE_ME_APP_NAME.fullname" . }}.office.angha.me
  {{ else if eq .Values.virtualService.productionGateway "internal-gateway.prod" -}}
  - {{ template "REPLACE_ME_APP_NAME.fullname" . }}.internal.angha.me
  {{ end -}}
  {{- else }}
  {{- if eq .Values.virtualService.stagingGateway "public-gateway.prod" -}}
  - {{ template "REPLACE_ME_APP_NAME.fullname" . }}.public.angha.me
  {{- else if eq .Values.virtualService.stagingGateway "private-gateway.prod" -}}
  - {{ template "REPLACE_ME_APP_NAME.fullname" . }}.office.angha.me
  {{- else if eq .Values.virtualService.stagingGateway "internal-gateway.prod" -}}
  - {{ template "REPLACE_ME_APP_NAME.fullname" . }}.internal.angha.me
  {{- end -}}
  {{- end }}
  gateways:
{{- if eq .Release.Name "prod" }}
  - {{ toYaml .Values.virtualService.productionGateway -}}
{{- else }}
  - {{ toYaml .Values.virtualService.stagingGateway -}}
{{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.externalPort }}
{{- end }}
